version: '0.2'
phases:
  pre_build:
    commands:
    - 'aws ecr get-login-password | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com'
  build:
    commands:
    - 'bash build.sh'
